# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: orgviewer-med-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{ toYaml .Values.orgviewer.med.environment | indent 2 }}
