---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.orgviewer.med.enabled }}
{{- $keycloak_client_id := "orgviewer" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgviewer-med-deployment
  labels:
    app: orgviewer-med
spec:
  selector:
    matchLabels:
      app: orgviewer-med
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orgviewer-med
    spec:
      containers:
        - name: orgviewer-med
          image: "{{ .Values.orgviewer.image.registry }}/{{ .Values.orgviewer.image.repository }}:{{ .Values.orgviewer.image.tag }}"
          env:
            {{- if not .Values.orgviewer.med.url }}
              {{- fail ".Values.orgviewer.med.url must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.med.title }}
              {{- fail ".Values.orgviewer.med.title must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.med.org_uuid }}
              {{- fail ".Values.orgviewer.med.org_uuid must be set" }}
            {{- end }}

            - name: GLOBAL_API_URL
              value: https://{{ .Values.ingress.hostname }}

            - name: GLOBAL_APP_TITLE
              value: {{ .Values.orgviewer.med.title }}

            - name: GLOBAL_API_ROOT_UUID
              value: {{ .Values.orgviewer.med.org_uuid }}

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orgviewer-client-secret
                  key: client_secret

            - name: GLOBAL_ORG_PERSON_RELATION
              value: "association"

            - name: CUSTOMER
              value: "default"

            - name: VUE_APP_TREE_LAYOUT
              value: "vertical"

            {{- range $name, $value := .Values.orgviewer.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if not .Values.orgviewer.environment }}
            {{- if .Values.orgviewer.extraEnv }}
            {{ toYaml .Values.orgviewer.extraEnv | indent 12 | trim }}
            {{- end }}
            {{- end }}

            {{- range $name, $value := .Values.orgviewer.med.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if not .Values.orgviewer.med.environment }}
            {{- if .Values.orgviewer.med.extraEnv }}
            {{ toYaml .Values.orgviewer.med.extraEnv | indent 12 | trim }}
            {{- end }}
            {{- end }}

          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.orgviewer.med.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_orgviewer

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: {{ $keycloak_client_id }}
            - name: TF_VAR_client_roles
              value: '["reader"]'
            - name: TF_VAR_client_standard_flow_enabled
              value: 'true'
            - name: TF_VAR_client_valid_redirect_urls
              value: '["*"]'
            - name: TF_VAR_client_web_origins
              value: '["*"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: orgviewer-client-secret
                  key: client_secret
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
