---
# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if .Values.orgviewer.med.enabled }}
{{- $keycloak_client_id := "integration_orgviewer_med" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orgviewer-med-deployment
  labels:
    app: orgviewer-med
spec:
  replicas: {{ .Values.orgviewer.med.replicaCount }}
  selector:
    matchLabels:
      app: orgviewer-med
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orgviewer-med
    spec:
      containers:
        - name: orgviewer-med
          {{- if and (ne .Values.orgviewer.image.tag "latest") (contains "." .Values.orgviewer.image.tag) }}
            {{- if (semverCompare "<2.3.0" .Values.orgviewer.image.tag) }}
              {{- fail "Orgviewer version must be at least 2.3.0" }}
            {{- end }}
          {{- end }}
          image: "{{ .Values.orgviewer.image.registry }}/{{ .Values.orgviewer.image.repository }}:{{ .Values.orgviewer.image.tag }}"
          imagePullPolicy: {{ .Values.orgviewer.image.pullPolicy }}
          env:
            {{- if not .Values.orgviewer.med.url }}
              {{- fail ".Values.orgviewer.med.url must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.med.title }}
              {{- fail ".Values.orgviewer.med.title must be set" }}
            {{- end }}
            {{- if not .Values.orgviewer.med.org_uuid }}
              {{- fail ".Values.orgviewer.med.org_uuid must be set" }}
            {{- end }}

            - name: GLOBAL_API_URL
              value: {{ .Values.ingress.hostname }}

            - name: GLOBAL_APP_TITLE
              value: {{ .Values.orgviewer.med.title }}

            - name: GLOBAL_API_ROOT_UUID
              value: {{ .Values.orgviewer.med.org_uuid }}

            - name: KEYCLOAK_CLIENT_ID
              value: {{ $keycloak_client_id }}

            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orgviewer-med-client-secret
                  key: client_secret

            - name: KEYCLOAK_BASEURL
              value: "{{ .Values.ingress.hostname }}/auth"

            - name: GLOBAL_ORG_PERSON_RELATION
              value: "association"

            - name: CUSTOMER
              value: "default"

            - name: VUE_APP_TREE_LAYOUT
              value: "vertical"
          envFrom:
            - configMapRef:
                name: orgviewer-environment-config
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.orgviewer.med.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mox" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.integrationbuilder.image.pullPolicy }}
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_orgviewer_med

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: {{ $keycloak_client_id }}
            - name: TF_VAR_client_roles
              value: '["reader"]'
            - name: TF_VAR_client_standard_flow_enabled
              value: 'true'
            - name: TF_VAR_client_valid_redirect_urls
              value: '["*"]'
            - name: TF_VAR_client_web_origins
              value: '["*"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: orgviewer-med-client-secret
                  key: client_secret
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
