# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- if or .Values.orgviewer.med.enabled .Values.orgviewer.adm.enabled }}
{{- if not (or .Values.os2mo.environment.KEYCLOAK_RBAC_ENABLED .Values.os2mo.environment.keycloak_rbac_enabled) }}
  {{- fail "You cannot deploy orgviewer without enabling RBAC in os2mo." -}}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: orgviewer-client-secret
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/autogenerate: client_secret
data: {}
{{- end }}
