# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---

{{- if or (.Values.orgviewer.adm.enabled) (.Values.orgviewer.med.enabled) }}
  {{- if not (or .Values.os2mo.environment.KEYCLOAK_RBAC_ENABLED .Values.os2mo.environment.keycloak_rbac_enabled) }}
    {{- fail "You cannot deploy orgviewer without enabling RBAC in os2mo." -}}
  {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: orgviewer-environment-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{ toYaml .Values.orgviewer.environment | indent 2 }}
