# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
os2mo:
  image:
    pullPolicy: Always
  replicaCount: 1
  gunicorn:
    max_workers: 1
  init:
    enabled: false
    image:
      tag: latest
      pullPolicy: Always
    config:
      root_organisation:
        name: xyz
        user_key: 702d97ea-4e03-11ec-8163-c70f41b96b32
      facets:
        org_unit_address_type:
          PhoneUnit:
            title: "CVR"
            scope: "CVR"
      it_systems: {}
    log_level: DEBUG
  db_init:
    make_superuser: true
  environment:
    GRAPHQL_ENABLE: true
    KEYCLOAK_VERIFY_AUDIENCE: false
  resources:
    requests:
      memory: "1024Mi"
      cpu: "500m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"

dipex:
  image:
    pullPolicy: Always

keycloak:
  init:
    image:
      pullPolicy: Always
  builder:
    image:
      pullPolicy: Always
    lora_realm_enabled: true
    lora_dipex_client_enabled: true
    environment:
      KEYCLOAK_SSL_REQUIRED_MO: none
      KEYCLOAK_SSL_REQUIRED_LORA: none
      KEYCLOAK_REALM_USERS: '[
        {
          "username": "bruce",
          "password": "bruce",
          "firstname": "Bruce",
          "lastname": "Lee",
          "email": "bruce@kung.fu",
          "roles": ["admin"],
          "enabled": true
        }
      ]'
  integrationbuilder:
    image:
      pullPolicy: Always
  resources:
    requests:
      memory: "2048Mi"
      cpu: "1000m"
    limits:
      memory: "4096Mi"
      cpu: "2000m"

omada:
  image:
    pullPolicy: Always

sd_changed_at:
  image:
    pullPolicy: Always
  init:
    image:
      pullPolicy: Always

sdtool:
  enabled: false
  image:
    pullPolicy: Always

fixture: "kolding"

orgviewer:
  image:
    pullPolicy: Always
  med:
    enabled: false
    url: http://orgviewer-med.example.com
    org_uuid: "f06ee470-9f17-566f-acbe-e938112d46d9"
    title: "Medarbejder organisation"
    ingress:
      hostname: orgviewer-med.example.com

  adm:
    enabled: false
    url: http://orgviewer-adm.example.com
    org_uuid: "fb2d158f-114e-5f67-8365-2c520cf10b58"
    title: "Administrativ organisation"
    ingress:
      hostname: orgviewer-adm.example.com

os2sync:
  enabled: false
  image:
    pullPolicy: Always
  # The municipality CVR
  municipality: 12345678
  db_host: mysql
