# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if and (.Values.sql_export.enabled) (.Values.sql_export.historic_state.cronjob_enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sql-export-historic
  labels:
    app: sql-export
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.sql_export.historic_state.cronjob_schedule | quote }}
  timeZone: {{ .Values.timezone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-sql-export
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl -X POST "http://sql-export-service:8000/trigger?resolve_dar=${RESOLVE_DAR}&historic=true"' ]
              env:
                - name: RESOLVE_DAR
                  value: {{ .Values.sql_export.resolve_dar | quote }}
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          restartPolicy: OnFailure
{{- end }}
