# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sql-export
  labels:
    app: sql-export
spec:
  selector:
    matchLabels:
      app: sql-export
  endpoints:
  - port: "8000"
{{- end }}
