# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.os2sync.enabled }}
{{- $keycloak_client_id := "integration_os2sync_export" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2sync-export
  labels:
    app: os2sync-export
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: os2sync-export
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: os2sync-export
    spec:
      containers:
        - name: os2sync-export
          image: "{{ .Values.os2sync.exporter.registry }}/{{ .Values.os2sync.exporter.repository }}:{{ .Values.os2sync.exporter.tag }}"
          imagePullPolicy: {{ .Values.os2sync.exporter.pullPolicy }}
          env:
            - name: Municipality
              value: {{ required "The Municipality ENV is missing" .Values.os2sync.municipality | quote }}
            - name: mora_base
              value: {{ .Values.os2sync.mora_base | default "http://mo-service:5000" | quote }}
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: os2sync-export-client-secret
                  key: client_secret
            - name: os2sync_top_unit_uuid
              value: {{ required "The top level uuid is missing" .Values.os2sync.os2sync_top_unit_uuid | quote }}
            - name: os2sync_api_url
              value: "http://os2sync-service:5000/api"
            - name: os2sync_log_level
              value: {{ .Values.os2sync.os2sync_log_level | default 20 | quote }}
            - name: os2sync_log_file
              value: {{ .Values.os2sync.os2sync_log_file | default "/tmp/os2sync_export.log" | quote }}
            - name: os2sync_hash_cache
              value: {{ .Values.os2sync.os2sync_hash_cache | default "/tmo/hash_cache" | quote }}
            - name: os2sync_xfer_cpr
              value: {{ .Values.os2sync.os2sync_xfer_cpr | default false | quote }}
            - name: os2sync_autowash
              value: {{ .Values.os2sync.os2sync_autowash | default true| quote }}
            - name: os2sync_ca_verify_os2sync
              value: {{ .Values.os2sync.os2sync_ca_verify_os2sync | default true | quote }}
            - name: os2sync_ca_verify_os2mo
              value: {{ .Values.os2sync.os2sync_ca_verify_os2mo | default true | quote }}
            - name: os2sync_phone_scope_classes
              value: {{ .Values.os2sync.os2sync_phone_scope_classes | default "[]" | quote }}
            - name: os2sync_email_scope_classes
              value: {{ .Values.os2sync.os2sync_email_scope_classes | default "[]" | quote }}
            - name: os2sync_ignored_unit_levels
              value: {{ .Values.os2sync.os2sync_ignored_unit_levels | default "[]" | quote }}
            - name: os2sync_ignored_unit_types
              value: {{ .Values.os2sync.os2sync_ignored_unit_types | default "[]" | quote }}
            - name: os2sync_templates
              value: {{ .Values.os2sync.os2sync_templates | default "{}" | quote }}
            - name: os2sync_sync_managers
              value: {{ .Values.os2sync.os2sync_sync_managers | default false | quote }}
            - name: os2sync_use_contact_for_tasks
              value: {{ .Values.os2sync.os2sync_use_contact_for_tasks | default false | quote }}
            - name: os2sync_employee_engagement_address
              value: {{ .Values.os2sync.os2sync_employee_engagement_address | default "[]" | quote }}
            - name: os2sync_uuid_from_it_systems
              value: {{ .Values.os2sync.os2sync_uuid_from_it_systems | default "[]" | quote }}
            - name: os2sync_truncate_length
              value: {{ .Values.os2sync.os2sync_truncate_length | default 200 | quote }}
            - name: os2sync_user_key_it_system_name
              value: {{ .Values.os2sync.os2sync_user_key_it_system_name | default "Active Directory" | quote }}
            - name: os2sync_filter_hierarchy_names
              value: {{ .Values.os2sync.os2sync_filter_hierarchy_names | default "[]" | quote }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.os2sync.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.integrationbuilder.image.pullPolicy }}
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_os2sync_export

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: {{ $keycloak_client_id }}
            - name: TF_VAR_client_roles
              value: '["reader"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: os2sync-export-client-secret
                  key: client_secret
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}

          
{{- end }}
