# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.os2sync.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: os2sync-export-service
  labels:
    app: os2sync-export
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: os2sync-export
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
{{- end }}
