# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if .Values.database.external }}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: mox-db
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
{{ end }}
