# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: os2mo-init-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config: |
{{ toYaml .Values.os2mo.init.config | indent 4}}
