# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mo-init-job
  labels:
    app: os2mo-init
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      labels:
        app: os2mo-init
    spec:
      containers:
        - name: os2mo-init
          image: "{{ .Values.os2mo.init.image.registry }}/{{ .Values.os2mo.init.image.repository }}:{{ .Values.os2mo.init.image.tag }}"
          env:
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: AUTH_REALM
              value: "mo"
            - name: CLIENT_ID
              value: "dipex"  # TODO: don't use dipex client
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: LOG_LEVEL
              value: {{ .Values.os2mo.init.log_level | quote }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "400m"
          volumeMounts:
           - name: os2mo-init-config-volume
             mountPath: /config
             readOnly: true
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
      restartPolicy: Never
      volumes:
        - name: os2mo-init-config-volume
          configMap:
            name: os2mo-init-config
            items:
              - key: config
                path: config.yml
