# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mo-service
spec:
  selector:
    matchLabels:
      app: mo
  endpoints:
    - port: "5000"
      metricRelabelings:
        - action: keep
          regex: "placeholder"
          sourceLabels:
            - __name__
{{- end }}
