# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{ if not .Values.os2mo.headless }}
apiVersion: v1
kind: Service
metadata:
  name: mo-naldo-service
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: mo-naldo
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
{{ end }}
