# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.ad_to_mo_sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-to-mo-sync-config
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{ toYaml .Values.ad_to_mo_sync.environment | indent 2 }}
{{- end }}
