# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.ad_to_mo_sync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ad-to-mo-sync-init-config
  labels:
    app: ad-to-mo-sync
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config: |
    facets:
      employee_address_type:
        AD-Email:
          title: "Email"
          scope: "EMAIL"
{{- end }}
