# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if and (.Values.sd_changed_at.enabled) (.Values.sd_changed_at.cronjob_enabled) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sd-changed-at
  labels:
    app: sd-changed-at
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.sd_changed_at.cronjob_schedule | quote }}
  timeZone: {{ .Values.timezone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-sd-changed-at
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl --silent --show-error --fail-with-body -X POST "http://sd-changed-at-service:8000/trigger"' ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          initContainers:
            {{ include "os2mo.wait-for-sd-changed-at" . | nindent 12 }}
          restartPolicy: OnFailure
{{- end }}
