# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.sd_changed_at.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sd-changed-at-init-config
  labels:
    app: sd-changed-at
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config: |
    it_systems:
      sd_uuid: "SD UUID"
{{- end }}
