# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.manager_terminator.enabled }}
{{- $keycloak_client_id := "integration_manager_terminator" }}
{{- if not .Values.amqp.enabled }}
  {{- fail "Must have AMQP enabled if manager-terminator is enabled" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-terminator
  labels:
    app: manager-terminator
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-terminator
  template:
    metadata:
      labels:
        app: manager-terminator
    spec:
      containers:
        - name: manager-terminator
          image: "{{ .Values.manager_terminator.image.registry }}/{{ .Values.manager_terminator.image.repository }}:{{ .Values.manager_terminator.image.tag }}"
          imagePullPolicy: {{ .Values.manager_terminator.image.pullPolicy }}
          env:
            - name: FASTRAMQPI__CLIENT_ID
              value: "{{ $keycloak_client_id }}"
            - name: FASTRAMQPI__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: manager-terminator-client-secret
                  key: client_secret
            - name: FASTRAMQPI__AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.amqp.url_secret }}
                  key: url
            {{ if .Values.sentry.environment }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sentry.secret }}
                  key: dsn
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment | quote }}
            {{ end }}
            {{- range $name, $value := .Values.manager_terminator.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.manager_terminator.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            periodSeconds: {{ .Values.manager_terminator.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.manager_terminator.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.manager_terminator.probes.liveness.failureThreshold }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        - name: create-client-secret
          image: "{{ .Values.keycloak.integrationbuilder.image.registry }}/{{ .Values.keycloak.integrationbuilder.image.repository }}:{{ .Values.keycloak.integrationbuilder.image.tag }}"
          imagePullPolicy: {{ .Values.keycloak.integrationbuilder.image.pullPolicy }}
          env:
            {{ include "os2mo.keycloak_terraform_db_connection" .  | nindent 12 }}
            - name: POSTGRES_SCHEMA_NAME
              value: terraform_remote_state_manager_terminator

            # Keycloak REST connection
            - name: TF_VAR_admin_password
              valueFrom:
                secretKeyRef:
                  name: {{ include "os2mo.keycloak_admin_secret" . }}
                  key: admin_password

            # Configuration of the client
            - name: TF_VAR_client_name
              value: "{{ $keycloak_client_id }}"
            - name: TF_VAR_client_roles
              value: '["admin"]'
            - name: TF_VAR_client_secret
              valueFrom:
                secretKeyRef:
                  name: manager-terminator-client-secret
                  key: client_secret
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
{{- end }}