# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.manager_terminator.enabled }}
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: manager-terminator
  labels:
    app: manager-terminator
spec:
  selector:
    matchLabels:
      app: manager-terminator
  endpoints:
  - port: "8000"
{{- end }}
{{- end }}
