# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.fkk.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fkk-database-secret
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
    secret-generator.v1.mittwald.de/encoding: base32
    secret-generator.v1.mittwald.de/autogenerate: database_password
data: {}
{{- end }}
