# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
{{- $env := .Values.sdtool_plus.environment -}}
{{- $hasMultipleInstIds := and $env (hasKey $env "mo_subtree_paths_for_root") -}}
{{- if and (.Values.sdtool_plus.enabled) (.Values.sdtool_plus.cronjob_enabled) ($hasMultipleInstIds) -}}
{{- $root_context := . }}
{{- $parsedJson := fromJson $env.mo_subtree_paths_for_root | keys -}}
{{- range $inst_id := $parsedJson }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sdtool-plus
  labels:
    app: sdtool-plus
  {{- with $.Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ get $.Values.sdtool_plus.cronjob_schedules $inst_id | quote }}
  timeZone: {{ $.Values.timezone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-sdtool-plus
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl --silent --show-error --fail-with-body -X POST "http://sdtool-plus-service:8000/trigger?institution_identifier={{ $inst_id }}"' ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          initContainers:
            {{ include "os2mo.wait-for-sdtool-plus" $root_context | nindent 12 }}
          restartPolicy: OnFailure
{{- end }}
{{- end }}
