# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0

# This file will soon be deprecated. We keep it for now to avoid breaking changes
# and remove it once we have switched from using the environment variable
# MO_SUBTREE_PATH_FOR_ROOT to the variable MO_SUBTREE_PATHS_FOR_ROOT
{{- $env := .Values.sdtool_plus.environment -}}
{{- $hasMultipleInstIds := and $env (hasKey $env "mo_subtree_paths_for_root") -}}
{{- if and (.Values.sdtool_plus.enabled) (.Values.sdtool_plus.cronjob_enabled) (not $hasMultipleInstIds) -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-sdtool-plus
  labels:
    app: sdtool-plus
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.sdtool_plus.cronjob_schedule | quote }}
  timeZone: {{ .Values.timezone | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob-sdtool-plus
              image: curlimages/curl
              command: ["/bin/sh","-c"]
              args: [ 'curl --silent --show-error --fail-with-body -X POST "http://sdtool-plus-service:8000/trigger"' ]
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "5m"
                limits:
                  memory: "128Mi"
                  cpu: "10m"
          initContainers:
            {{ include "os2mo.wait-for-sdtool-plus" . | nindent 12 }}
          restartPolicy: OnFailure
{{- end }}
