# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.omada.enabled }}
# TODO: see https://git.magenta.dk/rammearkitektur/os2mo-helm-chart/-/merge_requests/142#note_140651
{{- if not .Values.amqp.enabled }}
  {{- fail "Must have AMQP enabled if omada is enabled" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omada-deployment
  labels:
    app: omada
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omada
  strategy:
    type: Recreate  # we need to force Recreate strategy when using persistent volumes
  template:
    metadata:
      labels:
        app: omada
    spec:
      containers:
        - name: omada
          image: "{{ .Values.omada.image.registry }}/{{ .Values.omada.image.repository }}:{{ .Values.omada.image.tag }}"
          imagePullPolicy: {{ .Values.omada.image.pullPolicy }}
          env:
            - name: ENABLE_METRICS
              value: "True"

            # MO Auth
            # TODO: Use separate integration token instead of global dipex one
            - name: MO__AUTH__CLIENT_ID
              value: "dipex"
            - name: MO__AUTH__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: MO__AUTH__SERVER
              value: "http://keycloak-service:8080/auth"

            # MO AMQP
            # TODO: use separate integration AMQP user instead of global one
            - name: MO__AMQP__URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.amqp.url_secret }}
                  key: url

            # Omada
            - name: OMADA__URL
              value: "{{ .Values.omada.odata.url }}"
            - name: OMADA__INTERVAL
              value: "{{ .Values.omada.interval }}"

            # Omada OIDC
            {{- if .Values.omada.oidc.enabled }}
            - name: OMADA__OIDC__CLIENT_ID
              value: "{{ .Values.omada.oidc.client_id }}"
            - name: OMADA__OIDC__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.omada.oidc.client_secret_name }}
                  key: client_secret
            - name: OMADA__OIDC__TOKEN_ENDPOINT
              value: "{{ .Values.omada.oidc.token_endpoint }}"
            - name: OMADA__OIDC__SCOPE
              value: "{{ .Values.omada.oidc.scope }}"
            {{- end }}

            # Omada AMQP
            - name: OMADA__AMQP__URL
              valueFrom:
                secretKeyRef:
                  # TODO: use separate integration AMQP user instead of global one
                  name: {{ .Values.amqp.url_secret }}
                  key: url

          envFrom:
            - configMapRef:
                name: omada
          ports:
            - containerPort: 80
          volumeMounts:
            - name: omada-pv-storage
              mountPath: /data/
          resources:
            {{- toYaml .Values.omada.resources | nindent 12 }}
      initContainers:
        {{ include "os2mo.wait-for-keycloak" . | nindent 8 }}
        {{ include "os2mo.wait-for-mo" . | nindent 8 }}
        - name: os2mo-init
          image: "{{ .Values.os2mo.init.image.registry }}/{{ .Values.os2mo.init.image.repository }}:{{ .Values.os2mo.init.image.tag }}"
          imagePullPolicy: {{ .Values.os2mo.init.image.pullPolicy }}
          env:
            - name: AUTH_SERVER
              value: "http://keycloak-service:8080/auth"
            - name: MO_URL
              value: "http://mo-service:5000"
            - name: CLIENT_ID
              value: "dipex"
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-dipex-secret
                  key: client_secret
            - name: LORA_URL
              value: "http://mo-service:5000/lora"
          resources:
            {{- toYaml .Values.initContainers.resources | nindent 12 }}
          volumeMounts:
           - name: omada-init-config-volume
             mountPath: /config
             readOnly: true
      volumes:
        - name: omada-init-config-volume
          configMap:
            name: omada-init-config
            items:
              - key: config
                path: config.yml
        - name: omada-pv-storage
          persistentVolumeClaim:
            claimName: omada-pv-claim
      {{- if and .Values.omada.odata.ip .Values.omada.odata.hostname }}
      hostAliases:
        - ip: {{ .Values.omada.odata.ip }}
          hostnames:
            - {{ .Values.omada.odata.hostname }}
      {{- end }}
{{- end }}
