# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0
---
{{- if .Values.omada.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
{{- end }}
